loaders:
  batch_size: 1
  mirror_padding:
  - 16
  - 32
  - 32
  raw_internal_path: raw
  test:
    slice_builder:
      name: SliceBuilder
      patch_shape:
      - 64
      - 64
      - 64
      stride_shape:
      - 10
      - 10
      - 10
    transformer:
      raw:
      - name: Standardize
      - expand_dims: true
        name: ToTensor
manual_seed: 0
model:
  f_maps: 32
  final_sigmoid: true
  in_channels: 1
  is_segmentation: true
  layer_order: gcr
  name: UNet3D
  num_groups: 8
  out_channels: 1
predictor:
  name: StandardPredictor
