trainer:
  max_num_epochs: 1000
  eval_score_higher_is_better: true
  max_num_iterations: 150000
  log_after_iters: 250
  resume: null
  validate_after_iters: 100
eval_metric:
  name: MeanIoU
  ignore_index: null
loaders:
  dataset: StandardHDF5Dataset
  label_internal_path: /label
  num_workers: 0
  raw_internal_path: /raw
  train:
    slice_builder:
      name: TrivialSliceBuilder
    transformer:
      label:
      - expand_dims: true
        name: ToTensor
      raw:
      - name: Standardize
      - expand_dims: true
        name: ToTensor
  val:
    slice_builder:
      name: TrivialSliceBuilder
    transformer:
      label:
      - expand_dims: true
        name: ToTensor
      raw:
      - name: Standardize
      - expand_dims: true
        name: ToTensor
loss:
  ignore_index: null
  name: BCELoss
lr_scheduler:
  factor: 0.2
  mode: min
  name: ReduceLROnPlateau
  patience: 15
manual_seed: 0
model:
  in_channels: 1
  name: LogisticRegression
  out_channels: 1
optimizer:
  learning_rate: 0.0001
  weight_decay: 1.0e-05
