trainer:
  max_num_epochs: 1000
  eval_score_higher_is_better: true
  max_num_iterations: 150000
  log_after_iters: 250
  resume: null
  validate_after_iters: 1000
eval_metric:
  name: MeanIoU
  ignore_index: null
loaders:
  dataset: StandardPDBDataset
  num_workers: 0
  featurizer:
    - name: AtomLabel
    - name: PotentialGrid
  train:
    slice_builder:
      name: TrivialSliceBuilder
    pdb_transformer:
      - name: RandomRotate
    transformer:
      label:
      - name: RandomFlip
      - expand_dims: true
        name: ToTensor
      raw:
      - name: Standardize
        # If this is not supplied, local stats for each image will be computed across all channels
        channels:
          # If a certain axis is present, that will be standardized, otherwise not
          - axis: 1
            # Global stats. If not supplied, local stats for each image will be used
            stats:
              mean: 0.10963263717159216
              std: 0.5725709752031986
      - name: RandomFlip
      - expand_dims: true
        name: ToTensor
  val:
    slice_builder:
      name: TrivialSliceBuilder
    transformer:
      label:
      - expand_dims: true
        name: ToTensor
      raw:
      - name: Standardize
        channels:
          - axis : 1
            stats:
              mean: 0.10963263717159216
              std: 0.5725709752031986
      - expand_dims: true
        name: ToTensor
loss:
  ignore_index: null
  name: BCEDiceLoss
lr_scheduler:
  factor: 0.2
  mode: min
  name: ReduceLROnPlateau
  patience: 15
manual_seed: 0
model:
  f_maps: 32
  final_sigmoid: true
  layer_order: gcr
  num_groups: 8
  name: UNet3D
  out_channels: 1
optimizer:
  learning_rate: 0.0002
  weight_decay: 1.0e-05
