trainer:
  max_num_epochs: 1000
  eval_score_higher_is_better: false
  max_num_iterations: 150000
  # log_after_iters: 250
  log_after_iters: 250
  resume: null
  validate_after_iters: 1000
eval_metric:
  name: MeanIoU
  ignore_index: null
loaders:
  dataset: StandardHDF5Dataset
  label_internal_path: /label
  num_workers: 0
  raw_internal_path: /raw
  train:
    slice_builder:
      name: FilterSliceBuilder
      patch_shape: [64, 64, 64]
      slack_acceptance: 0.01
      stride_shape: [10, 10, 10]
      threshold: 0.6
    transformer:
      label:
      - name: RandomFlip
      - name: RandomRotate90
      - angle_spectrum: 20
        axes: [[2, 1]]
        mode: reflect
        name: RandomRotate
      - expand_dims: true
        name: ToTensor
      raw:
      - name: Standardize
      - name: RandomFlip
      - name: RandomRotate90
      - angle_spectrum: 20
        axes: [[2, 1]]
        mode: reflect
        name: RandomRotate
      - expand_dims: true
        name: ToTensor
  val:
    slice_builder:
      name: FilterSliceBuilder
      patch_shape: [64, 64, 64]
      slack_acceptance: 0.01
      stride_shape: [10, 10, 10]
      threshold: 0.4
    transformer:
      label:
      - expand_dims: true
        name: ToTensor
      raw:
      - name: Standardize
      - expand_dims: true
        name: ToTensor
loss:
  ignore_index: null
  name: BCEDiceLoss
#  skip_last_target: true
lr_scheduler:
  factor: 0.2
  mode: min
  name: ReduceLROnPlateau
  patience: 15
manual_seed: 0
model:
  f_maps: 32
  final_sigmoid: true
  in_channels: 1
  layer_order: gcr
  name: UNet3D
  num_groups: 8
  out_channels: 1
optimizer:
  learning_rate: 0.0002
  weight_decay: 1.0e-05