dataFolder: /home/lorenzo/deep_apbs/srcData/pdbbind_v2019_refined
pdb2pqrPath: /home/lorenzo/pymol/bin/pdb2pqr
dryRun: True
test:
- 2yfe
train:
- 3c39
- 4ncn
- 4bps
- 4b5w
- 3d2e
- 3w9r
- 4rra
- 4f6u
- 4oeu
- 3ewc
- 4zb6
- 3m3z
- 3c39
- 3eeb
- 1ikt
- 1o5a
- 3vvy
#- 4w97
#- 2b4l
#- 5c5t
#- 1q5k
#- 3i73
#- 6iiu
#- 1h0a
#- 3hp9
#- 5z99
val:
- 4qij