trainer:
  max_num_epochs: 2
  eval_score_higher_is_better: true
  max_num_iterations: 150000
  log_after_iters: 1
  resume: null
  validate_after_iters: 1
eval_metric:
  name: MeanIoU
  ignore_index: null
featurizer:
  - name: PotentialGrid
  - name: AtomLabel
transformer:
  - name: Standardize
  - name: RandomFlip
  - name: RandomRotate3D
loaders:
  batch_size: 2
  dataset: RandomDataset
  force_rotations: true
  fail_on_error: true
  grid_size: 65
loss:
  ignore_index: null
  name: BCEDiceLoss
lr_scheduler:
  factor: 0.2
  mode: min
  name: ReduceLROnPlateau
  patience: 15
manual_seed: 0
model:
  f_maps: 32
  final_sigmoid: true
  layer_order: gcr
  num_groups: 8
  name: UNet3D
  out_channels: 1
optimizer:
  learning_rate: 0.0002
  weight_decay: 1.0e-05