dataFolder: /home/lorenzo/deep_apbs/srcData/pdbbind_v2019_refined
pdb2pqrPath: /home/lorenzo/pymol/bin/pdb2pqr
tmpl_dir: /home/lorenzo/3dunet-cavity
test:
- 2yfe
train:
- 4us3
# - 3ao4
useClusters: true
val:
- 4qij
#- 1fch
# - 3f3e
#- 3u9q
#- 2fvd