dataFolder: /home/lorenzo/deep_apbs/srcData/pdbbind_v2019_refined
pdb2pqrPath: /home/lorenzo/pymol/bin/pdb2pqr
reuse_grids: true
test:
- 2yfe
train:
- 4us3
# - 3ao4
val:
- 4qij
#- 1fch
# - 3f3e
#- 3u9q
#- 2fvd